appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: B8EKwQXtIBeSEJGcCNLRvqL7oVZeOOs2VRyKLkzN9MmHaDgoPZowcCxkywc1fFC8jwgb4y3H730wKSU7xUSMQf7swkA4MaLOqq+Ffh0e9y5dKB7j4zcw3W9EbuRNx1TbHcERdp6q5LCREzYlGX9jcFOGohTaR2Ic6AAusg8KgcbjOXoIeL+7MHzYBkYcVoXSNJ4XhzV/MIDne8HvGPbOx8u1VRSdPWo29SsDo9F3odmsfpJX9Bh+t6hVG9XHxaFPiEXgbJE8J1PS/dWqIR4J3GDK8heRW3Gsqqtkv1919AeI9Y1TxRiSkY3oz2yZ1goV1qh/5J+sO6xxDoXQYDkrOOOsRe5rrBjFDrCFJq/5JJbo0hlnB3a2AxRf3vj0sjMqiCr96zTYgqf1Ns0f1yONiayKR/vZHARx6Df/RH7OX8br54L51B2ZmOc9oiMJrAim67ASX3MgnvkXNZKIOsSb+oSgo6g97Uoz7PRWifqgm5SGHr+zQXLqs9puIsgITxw563HqylrtU1t1Z/0I9/ggeYNQNGoZvFzAArWG6bvh+ZS5APGkkfZ50V1FSmuc5fVlWsWWTFj+RZk6NVGVZxWaNeWYaxwh9LF7V/EZxjS1crxaIs5WSE0+OJRNXJuHfpsqYKkmifxjD03kLk2GypoiHmrmd3xY2vP60LZI7IDBNOg=
