travis:
  secure:
    BINSTAR_TOKEN: cHQtfxffAC58JCmFjcHWSyyEuGvLX5PwVHNh1QwcpRKbHn48Xd14MFs5uS8zRf5aIW1jMe449RvziC11L75a4ij6ZRPZTpREfqVpGunv+oDLKvgGYHPA4A9DEJ2ajJGF1HNCWtg0Dld/8DNLzYpqbcY6ceVUgXr1UQ9W9fN/qwb4hwa9dA1zZ/SFop47SYaGEylfTzy0admsLvsmL/3wf6oLNW01ehWq6FvAS43q0g76Sln8ercfWKdAnVqjFFL/KL5kA/kvDR5PeOREydTxsU4Gt2XkgU5xi2Zs1xwsamQ6/Ga0SvWhim9f2idEemX3tzaS8ilErSfJlMlZvKRV0t0ARiumFPySGnx9ew0HlcTqJshmMqnHrTpZ34roKMXrd0KRY0oevk93RZCySohoIofK61YND+p+T3cpnkl1FNBfUnp7+2O30yVgHAy4nic6G1zL6nRuVmYDHyh73gZ2WUccaDnP9VFWJJAoIJqSyBh5vlL9OF2wKhSmDd107wNsb6hNLMSNC0Er5Ea3a2Ox1FAnrUKUqRnbyhsrKXkzE5xXEqIGfJLGriolSRk0+jXYvoINen6BUReIHgobCsgwWSYWTPwOG6cE3w1/L3qJC4FHQM3fqbQVGbukaJB1/sGrL10WPro4/Z+PimGeMDlTbU8+dOnPIgxREfU11mRd9xc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
